Issue #13 SQL script to create DB
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #16
Opened 2020-02-10 12:40 UTC by Aeeee

2020-02-10 13:26 UTC, nikaalin approved these changes

2020-02-10 23:49 UTC, ChirkinaTanya approved these changes

2020-02-11 08:36 UTC, JustRevolt requested changes

2020-02-11 08:36 UTC, JustRevolt commented on src/sql/Create_DB.sql
> +        ON UPDATE NO ACTION,
@Aeeee 
Я думаю, что при обновление паспорта, id паспорта у пользователя должен обновляться, чтобы не потерялись и не перемешались паспортные данные.

2020-02-11 10:23 UTC, JustRevolt approved these changes

2020-02-12 11:34 UTC, Nursatb approved these changes

2020-02-12 14:14 UTC, closed without merging