Issue #26 Create InvoiceEntity & enum InvoiceStatus
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #38
Opened 2020-02-14 08:54 UTC by nikaalin

2020-02-14 10:23 UTC, a-deriabin approved these changes

2020-02-14 11:19 UTC, JustRevolt approved these changes

2020-02-14 13:15 UTC, ChirkinaTanya approved these changes

2020-02-14 14:59 UTC, PavelEzhkov reviewed
Fix it

2020-02-14 14:59 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/entity/InvoiceEntity.java
> +        if (this == o) return true;
Where is braces {} ?
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf 12 page

2020-02-14 14:59 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/entity/InvoiceEntity.java
> +    private int totalPrice;
Why int?

2020-02-15 17:16 UTC, PavelEzhkov reviewed
One more thing

2020-02-15 17:18 UTC, PavelEzhkov requested changes

2020-02-15 17:18 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/entity/InvoiceEntity.java
> +
Where is invoice status?

2020-02-17 11:02 UTC, PavelEzhkov approved these changes

2020-02-17 11:03 UTC, merged