Issue #49 SQL script to clear DB
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #50
Opened 2020-02-16 10:10 UTC by JustRevolt

2020-02-17 11:19 UTC, nikaalin approved these changes

2020-02-17 14:45 UTC, a-deriabin requested changes

2020-02-17 14:45 UTC, Aeeee commented on src/main/resources/sql/Clear_DB.sql
> +    car_model
No newline at the end?

2020-02-17 16:09 UTC, JustRevolt commented on src/main/resources/sql/Clear_DB.sql
> +    car_model
Add newline

2020-02-17 16:26 UTC, a-deriabin approved these changes

2020-02-18 10:33 UTC, ChirkinaTanya approved these changes

2020-02-18 12:34 UTC, PavelEzhkov approved these changes

2020-02-18 12:34 UTC, merged