Issue #52 Create Driving_license
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #53
Opened 2020-02-17 10:14 UTC by Nursatb

2020-02-17 16:25 UTC, a-deriabin requested changes

2020-02-17 16:25 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/Driving_license.java
> +        if (!(o instanceof Driving_license)) return false;
https://www.oracle.com/technetwork/java/codeconventions-150003.pdf page 13
(need braces {} after 'if')

2020-02-17 16:25 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/Driving_license.java
> +        return getSerial_number().equals(that.getSerial_number());
this will fail e.g. if serial number is null

2020-02-17 16:25 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/Driving_license.java
> +    private String Serial_number;
check code convention (lowerCamelCase for method fields)

2020-02-17 16:25 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/Driving_license.java
> +public class Driving_license {
check code convention (UpperCamelCase for classes)

2020-02-20 21:22 UTC, nikaalin approved these changes

2020-02-21 07:29 UTC, a-deriabin requested changes

2020-02-21 07:29 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/DrivingLicense.java
> +                id == that.id &&
you compare by id in line `if (getId() != that.getId()) { return false; }`
and then compare by id again here

2020-02-21 07:29 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/DrivingLicense.java
> +                        Objects.equals(serialNumber, that.serialNumber)
same issue as above

2020-02-21 07:29 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/entity/DrivingLicense.java
> +    private Date expirationDate;
Use LocalDate here instead

2020-02-24 15:00 UTC, JustRevolt approved these changes

2020-02-24 15:13 UTC, a-deriabin approved these changes

2020-02-24 15:19 UTC, PavelEzhkov approved these changes

2020-02-24 15:20 UTC, merged