Issue #57 invoice dao
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #62
Opened 2020-02-19 12:10 UTC by nikaalin

2020-02-19 12:49 UTC, a-deriabin requested changes

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +    static final String DELETE_QUERY = "DELETE FROM INVOICE WHERE ID = ?";
these could be private?

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +    private void setInvoiceFieldsToStatement(InvoiceEntity invoice, PreparedStatement statement) throws SQLException {
Too long line

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            PreparedStatement statement = connection.prepareStatement(GET_QUERY, ResultSet.TYPE_SCROLL_SENSITIVE,
Long line

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            PreparedStatement statement = connection.prepareStatement(UPDATE_QUERY, ResultSet.TYPE_SCROLL_SENSITIVE,
Long line

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            PreparedStatement statement = connection.prepareStatement(DELETE_QUERY, ResultSet.TYPE_SCROLL_SENSITIVE,
Long line

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            PreparedStatement statement = connection.prepareStatement(SAVE_QUERY, ResultSet.TYPE_SCROLL_SENSITIVE,
Long line

2020-02-19 12:49 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            throw new RuntimeException(e);
Throw some kind of checked exception instead (e.g. it's very likely we'll want to know if there's no entity with such id and handle it gracefully)

2020-02-19 13:25 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            while (resultSet.next());
Check documentation on ResultSet.next().
TL;DR by default, result set points at nothing. Correct usage is `while (resultSet.next()) { ... }`, NOT do/while

2020-02-19 13:50 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +            connection.close();
What happens if SQLException is thrown before connection is closed?

2020-02-21 07:36 UTC, a-deriabin approved these changes

2020-02-21 08:57 UTC, JustRevolt approved these changes

2020-02-24 15:55 UTC, PavelEzhkov reviewed
fix it

2020-02-24 15:55 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/dao/InvoiceDao.java
> +import java.util.List;
Do you realy need all this imports?

2020-02-24 15:55 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoImpl/InvoiceDaoImpl.java
> +    private static final Logger log = LogManager.getLogger(InvoiceDaoImpl.class);
It is a constant

2020-02-24 15:55 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoImpl/InvoiceDaoImpl.java
> +package com.ifmo.epampractice.daoImpl;
package com.ifmo.epampractice.daoimpl;

2020-02-24 15:55 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoImpl/InvoiceDaoImpl.java
> +            throw new RuntimeException(e);
I think logger will be enough for us, because it is not a good idea to throw a generic exception

2020-02-25 07:58 UTC, PavelEzhkov reviewed
the same as in pull request #69

2020-02-26 09:58 UTC, merged