Issue #59 Implemented UsersDAO
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #63
Opened 2020-02-19 14:20 UTC by Aeeee

2020-02-20 12:11 UTC, JustRevolt commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            ResultSet resultSet = statement.executeQuery(GET_QUERY);
How method will complete, if you do not set parameter in Query statement?

2020-02-20 12:12 UTC, JustRevolt approved these changes

2020-02-20 12:12 UTC, JustRevolt commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            ResultSet resultSet = statement.executeQuery(GET_QUERY);
How method will complete, if you do not set parameter in Query statement?

2020-02-20 12:14 UTC, JustRevolt requested changes

2020-02-20 12:14 UTC, JustRevolt commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            ResultSet resultSet = statement.executeQuery(GET_QUERY);
How method will complete, if you do not set parameter in Query statement?

2020-02-20 18:08 UTC, JustRevolt approved these changes

2020-02-20 20:59 UTC, nikaalin approved these changes

2020-02-21 16:02 UTC, ChirkinaTanya approved these changes

2020-02-21 20:12 UTC, PavelEzhkov reviewed
You can do it better and merge dev, please

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +import com.ifmo.epampractice.dao.BasicDaoInterface;
unused import

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            //TODO: use logger when it will be set up.
we have the logger

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            return users;
you can use one return for the method

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            }
You have to close Statement and ResultSet as soon as you are finished with them or add  into try-with-resources

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +        DBConnectorInterface dbConnector = DBConnectorPostgres.getInstance();
You've wrote it  in each method. You can do it 1 time

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +    public void delete(UsersEntity entity) {
Did you try the method? 
`org.postgresql.util.PSQLException: ERROR: update or delete on table "users" violates foreign key constraint "orders_client_id_fkey" on table "orders"
  Detail: Key (id)=(1) is still referenced from table "orders".`

probably I have to update my db

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/dao/UsersDao.java
> +    void update(UsersEntity o);
Why "o"? userEntity will be better

2020-02-21 20:12 UTC, PavelEzhkov commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +            if (!resultSet.next()) {
is not the best way, the thing is that `!resultSet.next()` makes reading more confusing than just `resultSet.next()`
try:
```
            if (resultSet.next()) {
                return entityFromResultSet(resultSet);
            }
        } catch (SQLException e) {
          ...
        }
        return null;
```

2020-02-22 16:25 UTC, Nursatb approved these changes

2020-02-24 09:28 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/daoimpl/UsersDaoImpl.java
> +    public void delete(UsersEntity entity) {
The problem is in DDL code.
Created Issue #77 for this.

2020-02-24 14:10 UTC, merged