Issue #61 create CarDao
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #73
Opened 2020-02-21 09:21 UTC by JustRevolt

2020-02-21 09:24 UTC, nikaalin approved these changes

2020-02-21 10:37 UTC, a-deriabin approved these changes

2020-02-21 10:37 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/daoimpl/CarDaoImpl.java
> +    DBConnectorPostgres dbConnector = DBConnectorPostgres.getInstance();
could be private?

2020-02-21 10:37 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/daoimpl/CarDaoImpl.java
> +        final String sql = "SELECT * FROM car";
Move constants to class level

2020-02-21 10:37 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/daoimpl/CarDaoImpl.java
> +        final String sql = "SELECT * FROM car WHERE id = ?";
Move constants to class level

2020-02-21 10:38 UTC, a-deriabin approved these changes

2020-02-24 08:46 UTC, a-deriabin requested changes

2020-02-24 08:46 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/daoimpl/CarDaoImpl.java
> +    private final String GET_ALL_QUERY = "SELECT * FROM car";
constants should be private static final

2020-02-24 08:46 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/daoimpl/CarDaoImpl.java
> +        List<CarEntity> carEntityList = new LinkedList<>();
Why LinkedList?

2020-02-24 15:11 UTC, a-deriabin approved these changes

2020-02-24 19:27 UTC, PavelEzhkov approved these changes

2020-02-24 19:27 UTC, merged