Issue #75 Create PassportDao
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #83
Opened 2020-02-25 13:00 UTC by ChirkinaTanya

2020-02-25 13:20 UTC, JustRevolt approved these changes

2020-02-26 08:34 UTC, nikaalin approved these changes

2020-02-26 17:25 UTC, a-deriabin requested changes

2020-02-26 17:25 UTC, a-deriabin commented on src/main/java/com/ifmo/epampractice/dao/PassportDao.java
> +}
missing newline

2020-02-26 17:25 UTC, a-deriabin commented on src/main/java/com/ifmo/epampractice/daoimpl/PassportDaoImpl.java
> +    private static final Logger LOGGER = LogManager.getLogger(CarDaoImpl.class);
Every constant should be static final, but not every static final is a constant.
In this case, it's just a reference to a logger object.
(UPD: wait with fixing this, maybe it's a part of EPAM codestyle, waiting for mentors' reply)
(UPD2: yes, better make in non-upper case)

2020-02-26 17:25 UTC, a-deriabin commented on src/main/java/com/ifmo/epampractice/daoimpl/PassportDaoImpl.java
> +    private static final String UPDATE_QUERY = "UPDATE passport SET issue_country = ?, issuer = ?, issue_date = ?, expiration_date = ?, serial_number = ? WHERE id = ?";
long line

2020-02-26 17:25 UTC, a-deriabin commented on src/main/java/com/ifmo/epampractice/daoimpl/PassportDaoImpl.java
> +    private static final String SAVE_QUERY = "INSERT INTO passport (issue_country, issuer, issue_date, expiration_date, serial_number) VALUES (?, ?, ?, ?, ?)";
long line

2020-02-27 10:11 UTC, ChirkinaTanya commented on src/main/java/com/ifmo/epampractice/daoimpl/PassportDaoImpl.java
> +    private static final Logger LOGGER = LogManager.getLogger(CarDaoImpl.class);
Fixed

2020-02-27 10:11 UTC, ChirkinaTanya commented on src/main/java/com/ifmo/epampractice/daoimpl/PassportDaoImpl.java
> +    private static final String UPDATE_QUERY = "UPDATE passport SET issue_country = ?, issuer = ?, issue_date = ?, expiration_date = ?, serial_number = ? WHERE id = ?";
Fixed

2020-02-27 10:11 UTC, ChirkinaTanya commented on src/main/java/com/ifmo/epampractice/daoimpl/PassportDaoImpl.java
> +    private static final String SAVE_QUERY = "INSERT INTO passport (issue_country, issuer, issue_date, expiration_date, serial_number) VALUES (?, ?, ?, ?, ?)";
Fixed

2020-02-27 12:19 UTC, ChirkinaTanya commented on src/main/java/com/ifmo/epampractice/dao/PassportDao.java
> +}
fixed

2020-02-27 15:01 UTC, a-deriabin approved these changes

2020-02-27 18:27 UTC, PavelEzhkov approved these changes

2020-02-27 18:28 UTC, merged