Issue #79 Admin orders service
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #93
Opened 2020-02-27 13:46 UTC by JustRevolt

2020-02-27 16:06 UTC, a-deriabin requested changes

2020-02-27 16:06 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/serviceimpl/AdminOrdersServiceImpl.java
> +import java.util.Date;
Use LocalDate instead of Date

2020-02-27 16:06 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/serviceimpl/AdminOrdersServiceImpl.java
> +        OrderDao dao = new OrderDaoImpl();
why create DAO every method call?

2020-02-27 16:06 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/serviceimpl/AdminOrdersServiceImpl.java
> +        return usersEntity.getDrivingLicenseId() != 0 && usersEntity.getPassId() != 0;
Are you sure `0` and `null` is the same for this field? What happens if someone creates DrivingLicense with id=0?

2020-02-27 16:06 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/services/AdminOrdersService.java
> +    public void updateCarDamage(int orderId, String description, LocalDate accidentDate, int severity, BigDecimal repairCost);
Long lines

2020-03-01 17:41 UTC, nikaalin approved these changes

2020-03-02 14:00 UTC, Nursatb approved these changes

2020-03-02 17:57 UTC, a-deriabin approved these changes

2020-03-03 08:54 UTC, PavelEzhkov approved these changes

2020-03-03 08:54 UTC, merged