Issue #96 Create login controller & page
java-practice-spb-2020/epam-ifmo-java-practice-2020-2 pull request #97
Opened 2020-03-01 17:33 UTC by nikaalin

2020-03-02 17:55 UTC, Aeeee commented on src/main/java/com/ifmo/epampractice/controllers/LogInController.java
> +    private LogInService logInService = new LogInServiceImpl();
this one can be static

2020-03-02 17:56 UTC, Aeeee commented on src/main/webapp/login.jsp
> +--%>
do we need this header?

2020-03-02 17:56 UTC, a-deriabin approved these changes

2020-03-02 19:12 UTC, JustRevolt approved these changes

2020-03-03 09:05 UTC, PavelEzhkov approved these changes

2020-03-03 09:07 UTC, PavelEzhkov requested changes
You have to resolve merge conflict with src/main/webapp/WEB-INF/web.xml

2020-03-04 08:51 UTC, PavelEzhkov approved these changes

2020-03-04 08:51 UTC, merged